spring.application.name=photo-painter

# Server configuration
server.port=8082
server.servlet.context-path=/api/photo-painter

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/${MYSQL_DATABASE_SERVER}?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# AWS S3
aws.s3.bucket=my-coloring-app-pictures

# OpenAI
openai.api.key=YOUR_OPENAI_KEY

spring.ai.openai.api-key=${OPEN_AI_KEY}

spring.profiles.active=dev