server:
  port: 8080 # Gateway runs on port 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Authorization
              - Content-Type
              - Accept
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Credentials
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/user-auth/**
        - id: photo-painter
          uri: http://localhost:8082
          predicates:
            - Path=/api/photo-painter/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG